### ISSUE TITLE
Issue on rendering plots for kosko in dashboard

### ISSUE THREAD

**Issue by RodneyAndresPerez** [CSE583-Electric-Cooking/e-cook#10]
Suspecting it has to do with the path to .csv in `process_a2ei.py`

![image](https://github.com/CSE583-Electric-Cooking/e-cook/assets/147548462/710935f5-7225-402c-8c7b-5826fca6b3b3)

@amukherjee25, @saryasuda, and I are getting blank plots.

**Comment by ericbehling** [comment]
{'label': f"EM-{name_logic(i)}", 'value': name_logic(i)} ->  {'label': f"EM-{name_logic(i)}", 'value': i}
