### ISSUE TITLE
Survey Data Processing

### ISSUE THREAD

**Issue by amukherjee25** [CSE583-Electric-Cooking/e-cook#8]
Survey result data processing

- Disaggregate survey result data based on type of meter installed (Ex. Which neighborhoods have which type of meter installed (Kosko & A2EI))
- What type of appliances are being used in which neighborhood (e.g. percolator, hot plate, cookstove, EPC, etc.) → 1 indicates yes, 0 indicates no in survey data
- Who is electricity being paid to? (Kamyufu, Landlord, Neighbor, Umeme)
- Type of Connection (A - Individual metered, B - unmetered, C - Dual metered, D - Collective metered, E - collective unmetered, F - Dual collective metered)

**Comment by amukherjee25** [comment]
@ericbehling

**Comment by ericbehling** [comment]
done
